name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Build site
        working-directory: docs
        run: npm run build

      - name: Deploy to GitHub Pages
        working-directory: docs
        env:
          GIT_USER: github-actions
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
